# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='classes.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rclasses.proto\"l\n\x0cProfileProto\x12\x15\n\rserverAddress\x18\x01 \x01(\t\x12\x12\n\nserverPort\x18\x02 \x01(\r\x12\x13\n\x0bsessionName\x18\x03 \x01(\t\x12\x1c\n\x06sensor\x18\x04 \x03(\x0b\x32\x0c.SensorProto\"U\n\x0bSensorProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x12(\n\tparameter\x18\x03 \x03(\x0b\x32\x15.SensorParameterProto\"N\n\x14SensorParameterProto\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.SensorParameterValueProto\"B\n\x19SensorParameterValueProto\x12\x13\n\x0b\x64oubleValue\x18\x01 \x01(\x01\x12\x10\n\x08strValue\x18\x02 \x01(\t\"K\n\x15\x41\x63\x63\x65lerationDataProto\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\"C\n\rGyroDataProto\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\"_\n\tDataProto\x12\x30\n\x10\x61\x63\x63\x65lerationData\x18\x01 \x03(\x0b\x32\x16.AccelerationDataProto\x12 \n\x08gyroData\x18\x02 \x03(\x0b\x32\x0e.GyroDataProto\"1\n\x0eGyroDataProto2\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"9\n\x16\x41\x63\x63\x65lerationDataProto2\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"\x96\x01\n\x0cSensorUpdate\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0f\n\x07session\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x31\n\x10\x61\x63\x63\x65lerationData\x18\x04 \x01(\x0b\x32\x17.AccelerationDataProto2\x12!\n\x08gyroData\x18\x05 \x01(\x0b\x32\x0f.GyroDataProto2b\x06proto3')
)




_PROFILEPROTO = _descriptor.Descriptor(
  name='ProfileProto',
  full_name='ProfileProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverAddress', full_name='ProfileProto.serverAddress', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverPort', full_name='ProfileProto.serverPort', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionName', full_name='ProfileProto.sessionName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor', full_name='ProfileProto.sensor', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=125,
)


_SENSORPROTO = _descriptor.Descriptor(
  name='SensorProto',
  full_name='SensorProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SensorProto.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='SensorProto.status', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter', full_name='SensorProto.parameter', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=212,
)


_SENSORPARAMETERPROTO = _descriptor.Descriptor(
  name='SensorParameterProto',
  full_name='SensorParameterProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='SensorParameterProto.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='SensorParameterProto.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=292,
)


_SENSORPARAMETERVALUEPROTO = _descriptor.Descriptor(
  name='SensorParameterValueProto',
  full_name='SensorParameterValueProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doubleValue', full_name='SensorParameterValueProto.doubleValue', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strValue', full_name='SensorParameterValueProto.strValue', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=360,
)


_ACCELERATIONDATAPROTO = _descriptor.Descriptor(
  name='AccelerationDataProto',
  full_name='AccelerationDataProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='AccelerationDataProto.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='AccelerationDataProto.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='AccelerationDataProto.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='AccelerationDataProto.timestamp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=437,
)


_GYRODATAPROTO = _descriptor.Descriptor(
  name='GyroDataProto',
  full_name='GyroDataProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='GyroDataProto.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='GyroDataProto.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='GyroDataProto.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='GyroDataProto.timestamp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=506,
)


_DATAPROTO = _descriptor.Descriptor(
  name='DataProto',
  full_name='DataProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accelerationData', full_name='DataProto.accelerationData', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyroData', full_name='DataProto.gyroData', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=603,
)


_GYRODATAPROTO2 = _descriptor.Descriptor(
  name='GyroDataProto2',
  full_name='GyroDataProto2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='GyroDataProto2.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='GyroDataProto2.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='GyroDataProto2.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=654,
)


_ACCELERATIONDATAPROTO2 = _descriptor.Descriptor(
  name='AccelerationDataProto2',
  full_name='AccelerationDataProto2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='AccelerationDataProto2.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='AccelerationDataProto2.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='AccelerationDataProto2.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=656,
  serialized_end=713,
)


_SENSORUPDATE = _descriptor.Descriptor(
  name='SensorUpdate',
  full_name='SensorUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SensorUpdate.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session', full_name='SensorUpdate.session', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='SensorUpdate.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accelerationData', full_name='SensorUpdate.accelerationData', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyroData', full_name='SensorUpdate.gyroData', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=866,
)

_PROFILEPROTO.fields_by_name['sensor'].message_type = _SENSORPROTO
_SENSORPROTO.fields_by_name['parameter'].message_type = _SENSORPARAMETERPROTO
_SENSORPARAMETERPROTO.fields_by_name['value'].message_type = _SENSORPARAMETERVALUEPROTO
_DATAPROTO.fields_by_name['accelerationData'].message_type = _ACCELERATIONDATAPROTO
_DATAPROTO.fields_by_name['gyroData'].message_type = _GYRODATAPROTO
_SENSORUPDATE.fields_by_name['accelerationData'].message_type = _ACCELERATIONDATAPROTO2
_SENSORUPDATE.fields_by_name['gyroData'].message_type = _GYRODATAPROTO2
DESCRIPTOR.message_types_by_name['ProfileProto'] = _PROFILEPROTO
DESCRIPTOR.message_types_by_name['SensorProto'] = _SENSORPROTO
DESCRIPTOR.message_types_by_name['SensorParameterProto'] = _SENSORPARAMETERPROTO
DESCRIPTOR.message_types_by_name['SensorParameterValueProto'] = _SENSORPARAMETERVALUEPROTO
DESCRIPTOR.message_types_by_name['AccelerationDataProto'] = _ACCELERATIONDATAPROTO
DESCRIPTOR.message_types_by_name['GyroDataProto'] = _GYRODATAPROTO
DESCRIPTOR.message_types_by_name['DataProto'] = _DATAPROTO
DESCRIPTOR.message_types_by_name['GyroDataProto2'] = _GYRODATAPROTO2
DESCRIPTOR.message_types_by_name['AccelerationDataProto2'] = _ACCELERATIONDATAPROTO2
DESCRIPTOR.message_types_by_name['SensorUpdate'] = _SENSORUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProfileProto = _reflection.GeneratedProtocolMessageType('ProfileProto', (_message.Message,), dict(
  DESCRIPTOR = _PROFILEPROTO,
  __module__ = 'classes_pb2'
  # @@protoc_insertion_point(class_scope:ProfileProto)
  ))
_sym_db.RegisterMessage(ProfileProto)

SensorProto = _reflection.GeneratedProtocolMessageType('SensorProto', (_message.Message,), dict(
  DESCRIPTOR = _SENSORPROTO,
  __module__ = 'classes_pb2'
  # @@protoc_insertion_point(class_scope:SensorProto)
  ))
_sym_db.RegisterMessage(SensorProto)

SensorParameterProto = _reflection.GeneratedProtocolMessageType('SensorParameterProto', (_message.Message,), dict(
  DESCRIPTOR = _SENSORPARAMETERPROTO,
  __module__ = 'classes_pb2'
  # @@protoc_insertion_point(class_scope:SensorParameterProto)
  ))
_sym_db.RegisterMessage(SensorParameterProto)

SensorParameterValueProto = _reflection.GeneratedProtocolMessageType('SensorParameterValueProto', (_message.Message,), dict(
  DESCRIPTOR = _SENSORPARAMETERVALUEPROTO,
  __module__ = 'classes_pb2'
  # @@protoc_insertion_point(class_scope:SensorParameterValueProto)
  ))
_sym_db.RegisterMessage(SensorParameterValueProto)

AccelerationDataProto = _reflection.GeneratedProtocolMessageType('AccelerationDataProto', (_message.Message,), dict(
  DESCRIPTOR = _ACCELERATIONDATAPROTO,
  __module__ = 'classes_pb2'
  # @@protoc_insertion_point(class_scope:AccelerationDataProto)
  ))
_sym_db.RegisterMessage(AccelerationDataProto)

GyroDataProto = _reflection.GeneratedProtocolMessageType('GyroDataProto', (_message.Message,), dict(
  DESCRIPTOR = _GYRODATAPROTO,
  __module__ = 'classes_pb2'
  # @@protoc_insertion_point(class_scope:GyroDataProto)
  ))
_sym_db.RegisterMessage(GyroDataProto)

DataProto = _reflection.GeneratedProtocolMessageType('DataProto', (_message.Message,), dict(
  DESCRIPTOR = _DATAPROTO,
  __module__ = 'classes_pb2'
  # @@protoc_insertion_point(class_scope:DataProto)
  ))
_sym_db.RegisterMessage(DataProto)

GyroDataProto2 = _reflection.GeneratedProtocolMessageType('GyroDataProto2', (_message.Message,), dict(
  DESCRIPTOR = _GYRODATAPROTO2,
  __module__ = 'classes_pb2'
  # @@protoc_insertion_point(class_scope:GyroDataProto2)
  ))
_sym_db.RegisterMessage(GyroDataProto2)

AccelerationDataProto2 = _reflection.GeneratedProtocolMessageType('AccelerationDataProto2', (_message.Message,), dict(
  DESCRIPTOR = _ACCELERATIONDATAPROTO2,
  __module__ = 'classes_pb2'
  # @@protoc_insertion_point(class_scope:AccelerationDataProto2)
  ))
_sym_db.RegisterMessage(AccelerationDataProto2)

SensorUpdate = _reflection.GeneratedProtocolMessageType('SensorUpdate', (_message.Message,), dict(
  DESCRIPTOR = _SENSORUPDATE,
  __module__ = 'classes_pb2'
  # @@protoc_insertion_point(class_scope:SensorUpdate)
  ))
_sym_db.RegisterMessage(SensorUpdate)


# @@protoc_insertion_point(module_scope)
